spring:
  application.name: order-processor-tests
  datasource:
    url: "jdbc:tc:postgresql:16.4-alpine:///order-processor?TC_REUSABLE=true"
    hikari:
      minimum-idle: 2
      maximum-pool-size: 2
  liquibase:
    enabled: true
    contexts: integration
  cloud:
    aws:
      s3:
        enabled: false
      sqs:
        enabled: false

management:
  metrics:
    enable:
      tomcat: false
      jvm: false
      process: false
      hikaricp: false
      system: false
      jdbc: false
      http: false
      logback: false

logging:
  level:
    io.kraluk.orderprocessor: DEBUG
    org.jooq.tools.LoggerListener: INFO # DEBUG for SQL logs
    com.gruelbox.transactionoutbox.TransactionOutboxImpl: INFO

app:
  transaction-outbox:
    resumer-delay: PT1000H